name:  cli-worm
version: '0.01.02'
summary:  an epub reader for the command line
description: |
  A simple command line ncurses style interface for reading epubs

grade: stable
confinement: strict
apps:
  cli-worm:
    command: env LC_ALL=C.UTF-8 cli-worm # set LC_ALL env value when running to properly display utf8 characters
    plugs:
      - home
      - removable-media

parts:
  cli-worm:
    source: .
    plugin: nodejs
    node-engine: '9.11.2'
    stage-packages:
      - w3m # used to render xhtml to cli safe text
