name:  cli-worm # you probably want to 'snapcraft register <name>'
version: '0.0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary:  an epub reader for the command line # 79 char long summary
description: |
  A simple command line ncurses style interface for reading epubs

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  cli-worm:
    command: cli-worm

parts:
  cli-worm:
    # See 'snapcraft plugins'
    source: .
    plugin: nodejs
    node-engine: '8.11.1'
    stage-packages:
      - w3m
