name:  cli-worm
base: core20
version: '0.2.0'
summary:  an epub reader for the command line
description: |
  A simple command line ncurses style interface for reading epubs

grade: stable
confinement: strict
apps:
  cli-worm:
    command: env LC_ALL=C.UTF-8 cli-worm # set LC_ALL env value when running to properly display utf8 characters
    plugs:
      - home
      - removable-media

parts:
  cli-worm:
    source: .
    plugin: npm
    npm-node-version: v14.15.1
    override-build: |
      echo 'build start'
      pwd
      echo 'npm_config_unsafe_perm=true' >> ~/.npmrc
      echo 'npm_config_user=0' >> ~/.npmrc
      env npm_config_user=0
      env npm_config_unsafe_perm=true
      snapcraftctl build
    stage-packages:
      - w3m # used to render xhtml to cli safe text
      - gcc # Used to make sqllite compile correction on npm install
      - g++ # Used to make sqllite compile correction on npm install
      - libsqlite3-0
